version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: schoolmanagement
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    networks:
      - sm_network      
    volumes:
      - postgres_data:/data/postgres
       
    restart: unless-stopped
  keycloak:
    container_name: keycloak_Schoolmanagment
    image: quay.io/keycloak/keycloak:21.1.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres123     
      PROXY_ADDRESS_FORWARDING: true 
    ports:
      - "9090:8080"
    networks:
      - sm_network 
    depends_on:
      - postgres           
    command:
      - "start-dev"   
  schoolmanagement-api:
    container_name: schoolmanagement-api
    image: schoolmanagement/schoolmanagement:1.0.1
    ports:
      - 8080:8080
    networks:
      - sm_network
    depends_on:
      - postgres       
  pgadmin_sm:
    container_name: sm_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    networks:
      - sm_network      
    depends_on:
      - postgres      
    volumes:
      - ./backup:/backup  # Map the backup directory to your Windows host
    restart: unless-stopped
networks:
  sm_network:
    driver: bridge
volumes:
  postgres_data: