version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: defaultdb
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    networks:
      - sm_network      
    restart: unless-stopped
  keycloak:
    container_name: keycloak_Schoolmanagment
    image: quay.io/keycloak/keycloak:21.1.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres123      
    ports:
      - "9090:8080"
    networks:
      - sm_network      
    command:
      - "start-dev"    
  pgadmin_sm:
    container_name: sm_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    networks:
      - sm_network      
    restart: unless-stopped
networks:
  sm_network:
    driver: bridge
