CREATE TEMP TABLE tmp_alumno (LIKE alumno INCLUDING DEFAULTS);
\copy tmp_alumno (id, deleted, created_date, last_modified_date, created_by, last_modified_by, last_name, first_name, dni, birth_date, address, cuil, plan_social, trabaja, apellido_tutor, nombre_tutor, estudio_primario_tutor, estudio_secundario_tutor, estudio_ter_univ_tutor, dni_tutor, cuil_tutor, telefono1, telefono2, foto_dni, constancia_cuil, constancia6grado, acta_nacimiento, constancia_regular, foto4x4, foto_carnet_vac, ficha_medica, aptitud_fisica, grupo_sanguineo, ficha_inscripcion, libreta6grado, fotocopia_libro_matriz, fotocopia_dni_tutor, constancia_cuil_tutor, localidad_entity_id, parentesco_tutor_entity_id) FROM '/tmp/alumnos_sample.csv' WITH (FORMAT csv, HEADER true, DELIMITER ';');
INSERT INTO alumno SELECT * FROM tmp_alumno ON CONFLICT (id) DO UPDATE SET
  deleted = EXCLUDED.deleted,
  created_date = EXCLUDED.created_date,
  last_modified_date = EXCLUDED.last_modified_date,
  created_by = EXCLUDED.created_by,
  last_modified_by = EXCLUDED.last_modified_by,
  last_name = EXCLUDED.last_name,
  first_name = EXCLUDED.first_name,
  dni = EXCLUDED.dni,
  birth_date = EXCLUDED.birth_date,
  address = EXCLUDED.address,
  cuil = EXCLUDED.cuil,
  plan_social = EXCLUDED.plan_social,
  trabaja = EXCLUDED.trabaja,
  apellido_tutor = EXCLUDED.apellido_tutor,
  nombre_tutor = EXCLUDED.nombre_tutor,
  estudio_primario_tutor = EXCLUDED.estudio_primario_tutor,
  estudio_secundario_tutor = EXCLUDED.estudio_secundario_tutor,
  estudio_ter_univ_tutor = EXCLUDED.estudio_ter_univ_tutor,
  dni_tutor = EXCLUDED.dni_tutor,
  cuil_tutor = EXCLUDED.cuil_tutor,
  telefono1 = EXCLUDED.telefono1,
  telefono2 = EXCLUDED.telefono2,
  foto_dni = EXCLUDED.foto_dni,
  constancia_cuil = EXCLUDED.constancia_cuil,
  constancia6grado = EXCLUDED.constancia6grado,
  acta_nacimiento = EXCLUDED.acta_nacimiento,
  constancia_regular = EXCLUDED.constancia_regular,
  foto4x4 = EXCLUDED.foto4x4,
  foto_carnet_vac = EXCLUDED.foto_carnet_vac,
  ficha_medica = EXCLUDED.ficha_medica,
  aptitud_fisica = EXCLUDED.aptitud_fisica,
  grupo_sanguineo = EXCLUDED.grupo_sanguineo,
  ficha_inscripcion = EXCLUDED.ficha_inscripcion,
  libreta6grado = EXCLUDED.libreta6grado,
  fotocopia_libro_matriz = EXCLUDED.fotocopia_libro_matriz,
  fotocopia_dni_tutor = EXCLUDED.fotocopia_dni_tutor,
  constancia_cuil_tutor = EXCLUDED.constancia_cuil_tutor,
  localidad_entity_id = EXCLUDED.localidad_entity_id,
  parentesco_tutor_entity_id = EXCLUDED.parentesco_tutor_entity_id;
SELECT setval('alumno_id_seq', (SELECT MAX(id) FROM alumno));
