logging:
  level:
    org:
      springframework:
        web:
          servlet:
            mvc:
              method:
                annotation:
                  ExceptionHandlerExceptionResolver: TRACE
        transaction: TRACE
        security: TRACE
        beans:
          factory: DEBUG
      hibernate:
        engine:
          jdbc:
            sql:
              SqlExceptionHelper: DEBUG
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
spring:
  datasource:
    username: ${DB_USER:postgres}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:schoolmanagement}
    password: ${DB_PASSWORD:postgres123}
  sql:
    init:
      mode: ${SPRING_SQL_INIT_MODE:always}
  jpa:
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: ./target/create-schema.sql
      hibernate:
        check_nullability: 'true'
    defer-datasource-initialization: 'false' #This is useful for scenarios where schema.sql or data.sql scripts should run after Hibernate's schema generation. It must be set false for run flyway
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    show-sql: 'true'
  flyway:
    baseline-on-migrate: true
    enabled: ${SPRING_FLYWAY_ENABLED:true}
    user: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres123}
    baseline-description: "init"
    baseline-version: 0
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK:http://keycloak-sm:8080/realms/book-social-network}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200, https://warriorit.site, http://localhost:8081, http://localhost}
server:
    port: ${PORT:8088}
    forward-headers-strategy: ${SERVER_FORWARD_HEADERS_STRATEGY:native}

application:
  cors:
    origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200, https://warriorit.site, http://localhost:8081, http://localhost}