logging:
  level:
    org:
      springframework:
        web:
          servlet:
            mvc:
              method:
                annotation:
                  ExceptionHandlerExceptionResolver: TRACE
        transaction: TRACE
        security: TRACE
        beans:
          factory: DEBUG
      hibernate:
        engine:
          jdbc:
            sql:
              SqlExceptionHelper: DEBUG
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/schoolmanagement
    password: postgres123
  sql:
    init:
      mode: always
  jpa:
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: ./target/create-schema.sql
      hibernate:
        check_nullability: 'true'
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: none
    show-sql: 'true'
  flyway:
    baseline-on-migrate: true
    enabled: false
    user: postgres
    password: postgres123
    baseline-description: "init"
    baseline-version: 0
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://keycloak-sm:8080/realms/book-social-network"
  cors:
    allowed-origins: "http://localhost:4200, https://warriorit.site, http://localhost:8081, http://localhost"
server:
    port: 8088
    forward-headers-strategy: native