logging:
  level:
    org:
      springframework:
        security: TRACE
        beans:
          factory: DEBUG
spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/schoolmanagement
    password: postgres123
  sql:
    init:
      mode: always
  jpa:
    properties:
      hibernate:
        check_nullability: 'true'
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://keycloak-sm:8080/realms/book-social-network"
  cors:
    allowed-origins: "http://localhost:4200, https://warriorit.site, http://localhost:8081, http://localhost"
server:
    port: 8088
    forward-headers-strategy: native