logging:
  level:
    org:
      springframework:
        security: TRACE
        beans:
          factory: DEBUG
spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/schoolmanagement
    password: postgres123
  sql:
    init:
      mode: always
  jpa:
    properties:
      hibernate:
        check_nullability: 'true'
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: create
    show-sql: 'true'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/book-social-network"
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
server:
  port: 8088
  forward-headers-strategy: native