# Build stage
FROM maven:3.8.7-openjdk-18 AS build
WORKDIR /build
COPY pom.xml .
RUN mvn dependency:go-offline
COPY src ./src
RUN mvn clean package -DskipTests

# Runtime stage
FROM amazoncorretto:18
ARG PROFILE=dev
ARG APP_VERSION=1.0.1

WORKDIR /app
COPY --from=build /build/target/schoolmanagement-*.jar /app/

# Copy the certificate into the runtime image

COPY warriorit.site.crt /app/

# Import the certificate into the Java truststore
RUN keytool -importcert -noprompt \
    -file /app/warriorit.site.crt \
    -keystore $JAVA_HOME/lib/security/cacerts \
    -storepass changeit \
    -alias warriorit

# Extract the JAR version
RUN APP_VERSION=$(ls /app | grep *.jar | awk 'NR==2{split($0,a,"-"); print a[3]}' | awk '{sub(/.jar$/,"")}1')\
    && echo "Building container with BSN v-$version"
EXPOSE 8088

ENV DB_URL=jdbc:postgresql://postgres:5432/schoolmanagement
ENV MAILDEV_URL=localhost

ENV ACTIVE_PROFILE=${PROFILE}
ENV JAR_VERSION=${APP_VERSION}
ENV KEYCLOAK=https://www.warriorit.site/realms/book-social-network

CMD java -jar -Dspring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK} -Dspring.profiles.active=${ACTIVE_PROFILE} -Dspring.datasource.url=${DB_URL}  schoolmanagement-${JAR_VERSION}.jar

#docker build -t dom061077/sm-api:1.0.1 -f docker .