INSERT INTO provincia (id, nombre, deleted, created_date, last_modified_date, created_by, last_modified_by)
VALUES 
    (nextval('provincia_seq'), 'Buenos Aires', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM'),
    (nextval('provincia_seq'), 'Catamarca', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM'),
    (nextval('provincia_seq'), 'Chaco', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM'),
    (nextval('provincia_seq'), 'Chubut', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM'),
    (nextval('provincia_seq'), 'Ciudad Autónoma de Buenos Aires', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM'),
    (nextval('provincia_seq'), 'Córdoba', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM'),
    (nextval('provincia_seq'), 'Corrientes', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM'),
    (nextval('provincia_seq'), 'Entre Ríos', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM'),
    (nextval('provincia_seq'), 'Formosa', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM'),
    (nextval('provincia_seq'), 'Jujuy', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM'),
    (nextval('provincia_seq'), 'La Pampa', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM'),
    (nextval('provincia_seq'), 'La Rioja', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM'),
    (nextval('provincia_seq'), 'Mendoza', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM'),
    (nextval('provincia_seq'), 'Misiones', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM'),
    (nextval('provincia_seq'), 'Neuquén', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM'),
    (nextval('provincia_seq'), 'Río Negro', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM'),
    (nextval('provincia_seq'), 'Salta', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM'),
    (nextval('provincia_seq'), 'San Juan', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM'),
    (nextval('provincia_seq'), 'San Luis', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM'),
    (nextval('provincia_seq'), 'Santa Cruz', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM'),
    (nextval('provincia_seq'), 'Santa Fe', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM'),
    (nextval('provincia_seq'), 'Santiago del Estero', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM'),
    (nextval('provincia_seq'), 'Tierra del Fuego, Antártida e Islas del Atlántico Sur', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM'),
    (nextval('provincia_seq'), 'Tucumán', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM');
