INSERT INTO departamento (id, nombre, provincia_id, deleted, created_date, last_modified_date, created_by, last_modified_by)
SELECT 
    nextval('departamento_seq'), 
    d.nombre, 
    p.id, 
    false, 
    CURRENT_TIMESTAMP, 
    CURRENT_TIMESTAMP, 
    'SYSTEM', 
    'SYSTEM'
FROM (
    VALUES
        -- Ciudad Autónoma de Buenos Aires (15 Comunas)
        ('Ciudad Autónoma de Buenos Aires', 'Comuna 1'),
        ('Ciudad Autónoma de Buenos Aires', 'Comuna 2'),
        ('Ciudad Autónoma de Buenos Aires', 'Comuna 3'),
        ('Ciudad Autónoma de Buenos Aires', 'Comuna 4'),
        ('Ciudad Autónoma de Buenos Aires', 'Comuna 5'),
        ('Ciudad Autónoma de Buenos Aires', 'Comuna 6'),
        ('Ciudad Autónoma de Buenos Aires', 'Comuna 7'),
        ('Ciudad Autónoma de Buenos Aires', 'Comuna 8'),
        ('Ciudad Autónoma de Buenos Aires', 'Comuna 9'),
        ('Ciudad Autónoma de Buenos Aires', 'Comuna 10'),
        ('Ciudad Autónoma de Buenos Aires', 'Comuna 11'),
        ('Ciudad Autónoma de Buenos Aires', 'Comuna 12'),
        ('Ciudad Autónoma de Buenos Aires', 'Comuna 13'),
        ('Ciudad Autónoma de Buenos Aires', 'Comuna 14'),
        ('Ciudad Autónoma de Buenos Aires', 'Comuna 15'),

        -- Buenos Aires (135 Partidos)
        ('Buenos Aires', 'Adolfo Alsina'),
        ('Buenos Aires', 'Adolfo Gonzales Chaves'),
        ('Buenos Aires', 'Alberti'),
        ('Buenos Aires', 'Almirante Brown'),
        ('Buenos Aires', 'Arrecifes'),
        ('Buenos Aires', 'Avellaneda'),
        ('Buenos Aires', 'Ayacucho'),
        ('Buenos Aires', 'Azul'),
        ('Buenos Aires', 'Bahía Blanca'),
        ('Buenos Aires', 'Balcarce'),
        ('Buenos Aires', 'Baradero'),
        ('Buenos Aires', 'Benito Juárez'),
        ('Buenos Aires', 'Berazategui'),
        ('Buenos Aires', 'Berisso'),
        ('Buenos Aires', 'Bolívar'),
        ('Buenos Aires', 'Bragado'),
        ('Buenos Aires', 'Brandsen'),
        ('Buenos Aires', 'Campana'),
        ('Buenos Aires', 'Cañuelas'),
        ('Buenos Aires', 'Capitán Sarmiento'),
        ('Buenos Aires', 'Carlos Casares'),
        ('Buenos Aires', 'Carlos Tejedor'),
        ('Buenos Aires', 'Carmen de Areco'),
        ('Buenos Aires', 'Castelli'),
        ('Buenos Aires', 'Chacabuco'),
        ('Buenos Aires', 'Chascomús'),
        ('Buenos Aires', 'Chivilcoy'),
        ('Buenos Aires', 'Colón'),
        ('Buenos Aires', 'Coronel de Marina Leonardo Rosales'),
        ('Buenos Aires', 'Coronel Dorrego'),
        ('Buenos Aires', 'Coronel Pringles'),
        ('Buenos Aires', 'Coronel Suárez'),
        ('Buenos Aires', 'Daireaux'),
        ('Buenos Aires', 'Dolores'),
        ('Buenos Aires', 'Ensenada'),
        ('Buenos Aires', 'Escobar'),
        ('Buenos Aires', 'Esteban Echeverría'),
        ('Buenos Aires', 'Exaltación de la Cruz'),
        ('Buenos Aires', 'Ezeiza'),
        ('Buenos Aires', 'Florencio Varela'),
        ('Buenos Aires', 'Florentino Ameghino'),
        ('Buenos Aires', 'General Alvarado'),
        ('Buenos Aires', 'General Alvear'),
        ('Buenos Aires', 'General Arenales'),
        ('Buenos Aires', 'General Belgrano'),
        ('Buenos Aires', 'General Guido'),
        ('Buenos Aires', 'General Juan Madariaga'),
        ('Buenos Aires', 'General La Madrid'),
        ('Buenos Aires', 'General Las Heras'),
        ('Buenos Aires', 'General Lavalle'),
        ('Buenos Aires', 'General Paz'),
        ('Buenos Aires', 'General Pinto'),
        ('Buenos Aires', 'General Pueyrredón'),
        ('Buenos Aires', 'General Rodríguez'),
        ('Buenos Aires', 'General San Martín'),
        ('Buenos Aires', 'General Viamonte'),
        ('Buenos Aires', 'General Villegas'),
        ('Buenos Aires', 'Guaminí'),
        ('Buenos Aires', 'Hipólito Yrigoyen'),
        ('Buenos Aires', 'Hurlingham'),
        ('Buenos Aires', 'Ituzaingó'),
        ('Buenos Aires', 'José C. Paz'),
        ('Buenos Aires', 'Junín'),
        ('Buenos Aires', 'La Costa'),
        ('Buenos Aires', 'La Matanza'),
        ('Buenos Aires', 'La Plata'),
        ('Buenos Aires', 'Lanús'),
        ('Buenos Aires', 'Laprida'),
        ('Buenos Aires', 'Las Flores'),
        ('Buenos Aires', 'Leandro N. Alem'),
        ('Buenos Aires', 'Lezama'),
        ('Buenos Aires', 'Lincoln'),
        ('Buenos Aires', 'Lobería'),
        ('Buenos Aires', 'Lobos'),
        ('Buenos Aires', 'Lomas de Zamora'),
        ('Buenos Aires', 'Luján'),
        ('Buenos Aires', 'Magdalena'),
        ('Buenos Aires', 'Maipú'),
        ('Buenos Aires', 'Malvinas Argentinas'),
        ('Buenos Aires', 'Mar Chiquita'),
        ('Buenos Aires', 'Marcos Paz'),
        ('Buenos Aires', 'Mercedes'),
        ('Buenos Aires', 'Merlo'),
        ('Buenos Aires', 'Monte'),
        ('Buenos Aires', 'Monte Hermoso'),
        ('Buenos Aires', 'Moreno'),
        ('Buenos Aires', 'Morón'),
        ('Buenos Aires', 'Navarro'),
        ('Buenos Aires', 'Necochea'),
        ('Buenos Aires', 'Nueve de Julio'),
        ('Buenos Aires', 'Olavarría'),
        ('Buenos Aires', 'Patagones'),
        ('Buenos Aires', 'Pehuajó'),
        ('Buenos Aires', 'Pellegrini'),
        ('Buenos Aires', 'Pergamino'),
        ('Buenos Aires', 'Pila'),
        ('Buenos Aires', 'Pilar'),
        ('Buenos Aires', 'Pinamar'),
        ('Buenos Aires', 'Presidente Perón'),
        ('Buenos Aires', 'Puan'),
        ('Buenos Aires', 'Punta Indio'),
        ('Buenos Aires', 'Quilmes'),
        ('Buenos Aires', 'Ramallo'),
        ('Buenos Aires', 'Rauch'),
        ('Buenos Aires', 'Rivadavia'),
        ('Buenos Aires', 'Rojas'),
        ('Buenos Aires', 'Roque Pérez'),
        ('Buenos Aires', 'Saavedra'),
        ('Buenos Aires', 'Saladillo'),
        ('Buenos Aires', 'Salliqueló'),
        ('Buenos Aires', 'Salto'),
        ('Buenos Aires', 'San Andrés de Giles'),
        ('Buenos Aires', 'San Antonio de Areco'),
        ('Buenos Aires', 'San Cayetano'),
        ('Buenos Aires', 'San Fernando'),
        ('Buenos Aires', 'San Isidro'),
        ('Buenos Aires', 'San Miguel'),
        ('Buenos Aires', 'San Nicolás'),
        ('Buenos Aires', 'San Pedro'),
        ('Buenos Aires', 'San Vicente'),
        ('Buenos Aires', 'Suipacha'),
        ('Buenos Aires', 'Tandil'),
        ('Buenos Aires', 'Tapalqué'),
        ('Buenos Aires', 'Tigre'),
        ('Buenos Aires', 'Tordillo'),
        ('Buenos Aires', 'Tornquist'),
        ('Buenos Aires', 'Trenque Lauquen'),
        ('Buenos Aires', 'Tres Arroyos'),
        ('Buenos Aires', 'Tres de Febrero'),
        ('Buenos Aires', 'Tres Lomas'),
        ('Buenos Aires', 'Veinticinco de Mayo'),
        ('Buenos Aires', 'Vicente López'),
        ('Buenos Aires', 'Villa Gesell'),
        ('Buenos Aires', 'Villarino'),
        ('Buenos Aires', 'Zárate'),

        -- Catamarca (16 Departamentos)
        ('Catamarca', 'Ambato'),
        ('Catamarca', 'Ancasti'),
        ('Catamarca', 'Andalgalá'),
        ('Catamarca', 'Antofagasta de la Sierra'),
        ('Catamarca', 'Belén'),
        ('Catamarca', 'Capayán'),
        ('Catamarca', 'Capital'),
        ('Catamarca', 'El Alto'),
        ('Catamarca', 'Fray Mamerto Esquiú'),
        ('Catamarca', 'La Paz'),
        ('Catamarca', 'Paclín'),
        ('Catamarca', 'Pomán'),
        ('Catamarca', 'Santa María'),
        ('Catamarca', 'Santa Rosa'),
        ('Catamarca', 'Tinogasta'),
        ('Catamarca', 'Valle Viejo'),

        -- Chaco (25 Departamentos)
        ('Chaco', 'Almirante Brown'),
        ('Chaco', 'Bermejo'),
        ('Chaco', 'Chacabuco'),
        ('Chaco', 'Comandante Fernández'),
        ('Chaco', 'Doce de Octubre'),
        ('Chaco', 'Dos de Abril'),
        ('Chaco', 'Fray Justo Santa María de Oro'),
        ('Chaco', 'General Belgrano'),
        ('Chaco', 'General Donovan'),
        ('Chaco', 'General Güemes'),
        ('Chaco', 'Independencia'),
        ('Chaco', 'Libertad'),
        ('Chaco', 'Libertador General San Martín'),
        ('Chaco', 'Maipú'),
        ('Chaco', 'Mayor Luis Jorge Fontana'),
        ('Chaco', 'Nueve de Julio'),
        ('Chaco', 'O''Higgins'),
        ('Chaco', 'Presidencia de la Plaza'),
        ('Chaco', 'Primero de Mayo'),
        ('Chaco', 'Quitilipi'),
        ('Chaco', 'San Fernando'),
        ('Chaco', 'San Lorenzo'),
        ('Chaco', 'Sargento Cabral'),
        ('Chaco', 'Tapenagá'),
        ('Chaco', 'Veinticinco de Mayo'),

        -- Chubut (15 Departamentos)
        ('Chubut', 'Biedma'),
        ('Chubut', 'Cushamen'),
        ('Chubut', 'Escalante'),
        ('Chubut', 'Florentino Ameghino'),
        ('Chubut', 'Futaleufú'),
        ('Chubut', 'Gaiman'),
        ('Chubut', 'Gastre'),
        ('Chubut', 'Languiñeo'),
        ('Chubut', 'Mártires'),
        ('Chubut', 'Paso de Indios'),
        ('Chubut', 'Rawson'),
        ('Chubut', 'Río Senguer'),
        ('Chubut', 'Sarmiento'),
        ('Chubut', 'Tehuelches'),
        ('Chubut', 'Telsen'),

        -- Córdoba (26 Departamentos)
        ('Córdoba', 'Calamuchita'),
        ('Córdoba', 'Capital'),
        ('Córdoba', 'Colón'),
        ('Córdoba', 'Cruz del Eje'),
        ('Córdoba', 'General Roca'),
        ('Córdoba', 'General San Martín'),
        ('Córdoba', 'Ischilín'),
        ('Córdoba', 'Juárez Celman'),
        ('Córdoba', 'Marcos Juárez'),
        ('Córdoba', 'Minas'),
        ('Córdoba', 'Pocho'),
        ('Córdoba', 'Presidente Roque Sáenz Peña'),
        ('Córdoba', 'Punilla'),
        ('Córdoba', 'Río Cuarto'),
        ('Córdoba', 'Río Primero'),
        ('Córdoba', 'Río Seco'),
        ('Córdoba', 'Río Segundo'),
        ('Córdoba', 'San Alberto'),
        ('Córdoba', 'San Javier'),
        ('Córdoba', 'San Justo'),
        ('Córdoba', 'Santa María'),
        ('Córdoba', 'Sobremonte'),
        ('Córdoba', 'Tercero Arriba'),
        ('Córdoba', 'Totoral'),
        ('Córdoba', 'Tulumba'),
        ('Córdoba', 'Unión'),

        -- Corrientes (25 Departamentos)
        ('Corrientes', 'Bella Vista'),
        ('Corrientes', 'Berón de Astrada'),
        ('Corrientes', 'Capital'),
        ('Corrientes', 'Concepción'),
        ('Corrientes', 'Curuzú Cuatiá'),
        ('Corrientes', 'Empedrado'),
        ('Corrientes', 'Esquina'),
        ('Corrientes', 'General Alvear'),
        ('Corrientes', 'General Paz'),
        ('Corrientes', 'Goya'),
        ('Corrientes', 'Itatí'),
        ('Corrientes', 'Ituzaingó'),
        ('Corrientes', 'Lavalle'),
        ('Corrientes', 'Mburucuyá'),
        ('Corrientes', 'Mercedes'),
        ('Corrientes', 'Monte Caseros'),
        ('Corrientes', 'Paso de los Libres'),
        ('Corrientes', 'Saladas'),
        ('Corrientes', 'San Cosme'),
        ('Corrientes', 'San Luis del Palmar'),
        ('Corrientes', 'San Martín'),
        ('Corrientes', 'San Miguel'),
        ('Corrientes', 'San Roque'),
        ('Corrientes', 'Santo Tomé'),
        ('Corrientes', 'Sauce'),

        -- Entre Ríos (17 Departamentos)
        ('Entre Ríos', 'Colón'),
        ('Entre Ríos', 'Concordia'),
        ('Entre Ríos', 'Diamante'),
        ('Entre Ríos', 'Federación'),
        ('Entre Ríos', 'Federal'),
        ('Entre Ríos', 'Feliciano'),
        ('Entre Ríos', 'Gualeguay'),
        ('Entre Ríos', 'Gualeguaychú'),
        ('Entre Ríos', 'Islas del Ibicuy'),
        ('Entre Ríos', 'La Paz'),
        ('Entre Ríos', 'Nogoyá'),
        ('Entre Ríos', 'Paraná'),
        ('Entre Ríos', 'San Salvador'),
        ('Entre Ríos', 'Tala'),
        ('Entre Ríos', 'Uruguay'),
        ('Entre Ríos', 'Victoria'),
        ('Entre Ríos', 'Villaguay'),

        -- Formosa (9 Departamentos)
        ('Formosa', 'Bermejo'),
        ('Formosa', 'Formosa'),
        ('Formosa', 'Laishí'),
        ('Formosa', 'Matacos'),
        ('Formosa', 'Patiño'),
        ('Formosa', 'Pilagás'),
        ('Formosa', 'Pilcomayo'),
        ('Formosa', 'Pirané'),
        ('Formosa', 'Ramón Lista'),

        -- Jujuy (16 Departamentos)
        ('Jujuy', 'Cochinoca'),
        ('Jujuy', 'Doctor Manuel Belgrano'),
        ('Jujuy', 'El Carmen'),
        ('Jujuy', 'Humahuaca'),
        ('Jujuy', 'Ledesma'),
        ('Jujuy', 'Palpalá'),
        ('Jujuy', 'Rinconada'),
        ('Jujuy', 'San Antonio'),
        ('Jujuy', 'San Pedro'),
        ('Jujuy', 'Santa Bárbara'),
        ('Jujuy', 'Santa Catalina'),
        ('Jujuy', 'Susques'),
        ('Jujuy', 'Tilcara'),
        ('Jujuy', 'Tumbaya'),
        ('Jujuy', 'Valle Grande'),
        ('Jujuy', 'Yavi'),

        -- La Pampa (22 Departamentos)
        ('La Pampa', 'Atreucó'),
        ('La Pampa', 'Caleu Caleu'),
        ('La Pampa', 'Capital'),
        ('La Pampa', 'Catriló'),
        ('La Pampa', 'Chalileo'),
        ('La Pampa', 'Chapaleufú'),
        ('La Pampa', 'Chical Co'),
        ('La Pampa', 'Conhelo'),
        ('La Pampa', 'Curacó'),
        ('La Pampa', 'Guatraché'),
        ('La Pampa', 'Hucal'),
        ('La Pampa', 'Lihuel Calel'),
        ('La Pampa', 'Limay Mahuida'),
        ('La Pampa', 'Loventué'),
        ('La Pampa', 'Maracó'),
        ('La Pampa', 'Puelén'),
        ('La Pampa', 'Quemú Quemú'),
        ('La Pampa', 'Rancul'),
        ('La Pampa', 'Realicó'),
        ('La Pampa', 'Toay'),
        ('La Pampa', 'Trenel'),
        ('La Pampa', 'Utracán'),

        -- La Rioja (18 Departamentos)
        ('La Rioja', 'Arauco'),
        ('La Rioja', 'Capital'),
        ('La Rioja', 'Castro Barros'),
        ('La Rioja', 'Chamical'),
        ('La Rioja', 'Chilecito'),
        ('La Rioja', 'Coronel Felipe Varela'),
        ('La Rioja', 'Famatina'),
        ('La Rioja', 'General Ángel Vicente Peñaloza'),
        ('La Rioja', 'General Belgrano'),
        ('La Rioja', 'General Juan Facundo Quiroga'),
        ('La Rioja', 'General Lamadrid'),
        ('La Rioja', 'General Ocampo'),
        ('La Rioja', 'General San Martín'),
        ('La Rioja', 'Independencia'),
        ('La Rioja', 'Rosario Vera Peñaloza'),
        ('La Rioja', 'San Blas de los Sauces'),
        ('La Rioja', 'Sanagasta'),
        ('La Rioja', 'Vinchina'),

        -- Mendoza (18 Departamentos)
        ('Mendoza', 'Capital'),
        ('Mendoza', 'General Alvear'),
        ('Mendoza', 'Godoy Cruz'),
        ('Mendoza', 'Guaymallén'),
        ('Mendoza', 'Junín'),
        ('Mendoza', 'La Paz'),
        ('Mendoza', 'Las Heras'),
        ('Mendoza', 'Lavalle'),
        ('Mendoza', 'Luján de Cuyo'),
        ('Mendoza', 'Maipú'),
        ('Mendoza', 'Malargüe'),
        ('Mendoza', 'Rivadavia'),
        ('Mendoza', 'San Carlos'),
        ('Mendoza', 'San Martín'),
        ('Mendoza', 'San Rafael'),
        ('Mendoza', 'Santa Rosa'),
        ('Mendoza', 'Tunuyán'),
        ('Mendoza', 'Tupungato'),

        -- Misiones (17 Departamentos)
        ('Misiones', 'Apóstoles'),
        ('Misiones', 'Cainguás'),
        ('Misiones', 'Candelaria'),
        ('Misiones', 'Capital'),
        ('Misiones', 'Concepción'),
        ('Misiones', 'Eldorado'),
        ('Misiones', 'General Manuel Belgrano'),
        ('Misiones', 'Guaraní'),
        ('Misiones', 'Iguazú'),
        ('Misiones', 'Leandro N. Alem'),
        ('Misiones', 'Libertador General San Martín'),
        ('Misiones', 'Montecarlo'),
        ('Misiones', 'Oberá'),
        ('Misiones', 'San Ignacio'),
        ('Misiones', 'San Javier'),
        ('Misiones', 'San Pedro'),
        ('Misiones', 'Veinticinco de Mayo'),

        -- Neuquén (16 Departamentos)
        ('Neuquén', 'Aluminé'),
        ('Neuquén', 'Añelo'),
        ('Neuquén', 'Catán Lil'),
        ('Neuquén', 'Chos Malal'),
        ('Neuquén', 'Collón Curá'),
        ('Neuquén', 'Confluencia'),
        ('Neuquén', 'Huiliches'),
        ('Neuquén', 'Lácar'),
        ('Neuquén', 'Loncopué'),
        ('Neuquén', 'Los Lagos'),
        ('Neuquén', 'Minas'),
        ('Neuquén', 'Ñorquín'),
        ('Neuquén', 'Pehuenches'),
        ('Neuquén', 'Picún Leufú'),
        ('Neuquén', 'Picunches'),
        ('Neuquén', 'Zapala'),

        -- Río Negro (13 Departamentos)
        ('Río Negro', 'Adolfo Alsina'),
        ('Río Negro', 'Avellaneda'),
        ('Río Negro', 'Bariloche'),
        ('Río Negro', 'Conesa'),
        ('Río Negro', 'El Cuy'),
        ('Río Negro', 'General Roca'),
        ('Río Negro', 'Nueve de Julio'),
        ('Río Negro', 'Ñorquincó'),
        ('Río Negro', 'Pichi Mahuida'),
        ('Río Negro', 'Pilcaniyeu'),
        ('Río Negro', 'San Antonio'),
        ('Río Negro', 'Valcheta'),
        ('Río Negro', 'Veinticinco de Mayo'),

        -- Salta (23 Departamentos)
        ('Salta', 'Anta'),
        ('Salta', 'Cachi'),
        ('Salta', 'Cafayate'),
        ('Salta', 'Capital'),
        ('Salta', 'Cerrillos'),
        ('Salta', 'Chicoana'),
        ('Salta', 'General Güemes'),
        ('Salta', 'General José de San Martín'),
        ('Salta', 'Guachipas'),
        ('Salta', 'Iruya'),
        ('Salta', 'La Caldera'),
        ('Salta', 'La Candelaria'),
        ('Salta', 'La Poma'),
        ('Salta', 'La Viña'),
        ('Salta', 'Los Andes'),
        ('Salta', 'Metán'),
        ('Salta', 'Molinos'),
        ('Salta', 'Orán'),
        ('Salta', 'Rivadavia'),
        ('Salta', 'Rosario de la Frontera'),
        ('Salta', 'Rosario de Lerma'),
        ('Salta', 'San Carlos'),
        ('Salta', 'Santa Victoria'),

        -- San Juan (19 Departamentos)
        ('San Juan', 'Albardón'),
        ('San Juan', 'Angaco'),
        ('San Juan', 'Calingasta'),
        ('San Juan', 'Capital'),
        ('San Juan', 'Caucete'),
        ('San Juan', 'Chimbas'),
        ('San Juan', 'Iglesia'),
        ('San Juan', 'Jáchal'),
        ('San Juan', 'Nueve de Julio'),
        ('San Juan', 'Pocito'),
        ('San Juan', 'Rawson'),
        ('San Juan', 'Rivadavia'),
        ('San Juan', 'San Martín'),
        ('San Juan', 'Santa Lucía'),
        ('San Juan', 'Sarmiento'),
        ('San Juan', 'Ullum'),
        ('San Juan', 'Valle Fértil'),
        ('San Juan', 'Veinticinco de Mayo'),
        ('San Juan', 'Zonda'),

        -- San Luis (9 Departamentos)
        ('San Luis', 'Ayacucho'),
        ('San Luis', 'Belgrano'),
        ('San Luis', 'Chacabuco'),
        ('San Luis', 'Coronel Pringles'),
        ('San Luis', 'General Pedernera'),
        ('San Luis', 'Gobernador Dupuy'),
        ('San Luis', 'Juan Martín de Pueyrredón'),
        ('San Luis', 'Junín'),
        ('San Luis', 'Libertador General San Martín'),

        -- Santa Cruz (7 Departamentos)
        ('Santa Cruz', 'Corpen Aike'),
        ('Santa Cruz', 'Deseado'),
        ('Santa Cruz', 'Güer Aike'),
        ('Santa Cruz', 'Lago Argentino'),
        ('Santa Cruz', 'Lago Buenos Aires'),
        ('Santa Cruz', 'Magallanes'),
        ('Santa Cruz', 'Río Chico'),

        -- Santa Fe (19 Departamentos)
        ('Santa Fe', 'Belgrano'),
        ('Santa Fe', 'Caseros'),
        ('Santa Fe', 'Castellanos'),
        ('Santa Fe', 'Constitución'),
        ('Santa Fe', 'Garay'),
        ('Santa Fe', 'General López'),
        ('Santa Fe', 'General Obligado'),
        ('Santa Fe', 'Iriondo'),
        ('Santa Fe', 'La Capital'),
        ('Santa Fe', 'Las Colonias'),
        ('Santa Fe', 'Nueve de Julio'),
        ('Santa Fe', 'Rosario'),
        ('Santa Fe', 'San Cristóbal'),
        ('Santa Fe', 'San Javier'),
        ('Santa Fe', 'San Jerónimo'),
        ('Santa Fe', 'San Justo'),
        ('Santa Fe', 'San Lorenzo'),
        ('Santa Fe', 'San Martín'),
        ('Santa Fe', 'Vera'),

        -- Santiago del Estero (27 Departamentos)
        ('Santiago del Estero', 'Aguirre'),
        ('Santiago del Estero', 'Alberdi'),
        ('Santiago del Estero', 'Atamisqui'),
        ('Santiago del Estero', 'Avellaneda'),
        ('Santiago del Estero', 'Banda'),
        ('Santiago del Estero', 'Belgrano'),
        ('Santiago del Estero', 'Capital'),
        ('Santiago del Estero', 'Choya'),
        ('Santiago del Estero', 'Copo'),
        ('Santiago del Estero', 'Figueroa'),
        ('Santiago del Estero', 'General Taboada'),
        ('Santiago del Estero', 'Guasayán'),
        ('Santiago del Estero', 'Jiménez'),
        ('Santiago del Estero', 'Juan Felipe Ibarra'),
        ('Santiago del Estero', 'Loreto'),
        ('Santiago del Estero', 'Mitre'),
        ('Santiago del Estero', 'Moreno'),
        ('Santiago del Estero', 'Ojo de Agua'),
        ('Santiago del Estero', 'Pellegrini'),
        ('Santiago del Estero', 'Quebrachos'),
        ('Santiago del Estero', 'Río Hondo'),
        ('Santiago del Estero', 'Rivadavia'),
        ('Santiago del Estero', 'Robles'),
        ('Santiago del Estero', 'Salavina'),
        ('Santiago del Estero', 'San Martín'),
        ('Santiago del Estero', 'Sarmiento'),
        ('Santiago del Estero', 'Silípica'),

        -- Tierra del Fuego, Antártida e Islas del Atlántico Sur (5 Departamentos)
        ('Tierra del Fuego, Antártida e Islas del Atlántico Sur', 'Antártida Argentina'),
        ('Tierra del Fuego, Antártida e Islas del Atlántico Sur', 'Islas del Atlántico Sur'),
        ('Tierra del Fuego, Antártida e Islas del Atlántico Sur', 'Río Grande'),
        ('Tierra del Fuego, Antártida e Islas del Atlántico Sur', 'Tolhuin'),
        ('Tierra del Fuego, Antártida e Islas del Atlántico Sur', 'Ushuaia'),

        -- Tucumán (17 Departamentos)
        ('Tucumán', 'Burruyacú'),
        ('Tucumán', 'Capital'),
        ('Tucumán', 'Chicligasta'),
        ('Tucumán', 'Cruz Alta'),
        ('Tucumán', 'Famaillá'),
        ('Tucumán', 'Graneros'),
        ('Tucumán', 'Juan Bautista Alberdi'),
        ('Tucumán', 'La Cocha'),
        ('Tucumán', 'Leales'),
        ('Tucumán', 'Lules'),
        ('Tucumán', 'Monteros'),
        ('Tucumán', 'Río Chico'),
        ('Tucumán', 'Simoca'),
        ('Tucumán', 'Tafí del Valle'),
        ('Tucumán', 'Tafí Viejo'),
        ('Tucumán', 'Trancas'),
        ('Tucumán', 'Yerba Buena')
) AS d(provincia_nombre, nombre)
JOIN provincia p ON p.nombre = d.provincia_nombre;
