alter table if exists alumno alter column created_date set data type timestamp(6);
alter table if exists alumno alter column last_modified_date set data type timestamp(6);
alter table if exists departamento alter column created_date set data type timestamp(6);
alter table if exists departamento alter column last_modified_date set data type timestamp(6);
create table escuela (id bigint not null, created_by varchar(255), created_date timestamp(6), deleted boolean not null, last_modified_by varchar(255), last_modified_date timestamp(6), cue varchar(255) not null, name varchar(255) not null, primary key (id));
alter table if exists localidad alter column created_date set data type timestamp(6);
alter table if exists localidad alter column last_modified_date set data type timestamp(6);
alter table if exists menu alter column created_date set data type timestamp(6);
alter table if exists menu alter column last_modified_date set data type timestamp(6);
alter table if exists menu_role alter column created_date set data type timestamp(6);
alter table if exists menu_role alter column last_modified_date set data type timestamp(6);
alter table if exists parentesco_tutor alter column created_date set data type timestamp(6);
alter table if exists parentesco_tutor alter column last_modified_date set data type timestamp(6);
alter table if exists person alter column created_date set data type timestamp(6);
alter table if exists person alter column last_modified_date set data type timestamp(6);
alter table if exists provincia alter column created_date set data type timestamp(6);
alter table if exists provincia alter column last_modified_date set data type timestamp(6);
alter table if exists translation alter column created_date set data type timestamp(6);
alter table if exists translation alter column last_modified_date set data type timestamp(6);
create sequence escuela_seq start with 1 increment by 50;
