create sequence examenes_escolares_seq start with 1 increment by 50;
create sequence inscripcion_alumno_seq start with 1 increment by 50;
create sequence materia_seq start with 1 increment by 50;
create sequence nivel_grado_seq start with 1 increment by 50;
create sequence periodo_academico_seq start with 1 increment by 50;
create sequence periodo_lectivo_seq start with 1 increment by 50;
create sequence tipo_examen_seq start with 1 increment by 50;
create sequence tipo_periodo_academico_seq start with 1 increment by 50;
create table detalle_examenes_escolares (calificacion numeric(38,2), deleted boolean not null, created_date timestamp(6), id bigint not null, id_examen_escolar bigint, id_inscripcion_alumno bigint, id_periodo_lectivo bigint, last_modified_date timestamp(6), created_by varchar(255), last_modified_by varchar(255), primary key (id));
create table examenes_escolares (date date, deleted boolean not null, created_date timestamp(6), id bigint not null, id_docente bigint, id_materia bigint, id_periodo_lectivo bigint, id_tipo_examen bigint, last_modified_date timestamp(6), created_by varchar(255), description varchar(255), last_modified_by varchar(255), name varchar(255), primary key (id));
create table periodo_academico (cantidad_dias_escolares integer, deleted boolean not null, created_date timestamp(6), id bigint not null, last_modified_date timestamp(6), created_by varchar(255), last_modified_by varchar(255), primary key (id));
create table tipo_examen (deleted boolean not null, created_date timestamp(6), id bigint not null, last_modified_date timestamp(6), school_exam_id bigint, created_by varchar(255), description varchar(255), last_modified_by varchar(255), name varchar(255), primary key (id));
create table tipo_periodo_academico (id bigint not null, description varchar(255), name varchar(255), primary key (id));
create table materia (deleted boolean not null, created_date timestamp(6), docente_id bigint, id bigint not null, last_modified_date timestamp(6), nivel_grado_id bigint, created_by varchar(255), last_modified_by varchar(255), name varchar(255), primary key (id));
ALTER TABLE if exists inscripcion_alumno RENAME COLUMN student_id TO alumno_id;
ALTER TABLE if exists inscripcion_alumno RENAME COLUMN academic_period_id TO periodo_lectivo_id;
ALTER TABLE if exists inscripcion_alumno RENAME COLUMN grade_level_id TO nivel_grado_id;
ALTER TABLE if exists inscripcion_alumno RENAME COLUMN shift_id TO turno_id;
ALTER TABLE if exists inscripcion_alumno RENAME COLUMN section_id TO division_id;
alter table if exists detalle_examenes_escolares add constraint FKkfke7ux4ci01pqpkp4h3l10vq foreign key (id_periodo_lectivo) references periodo_lectivo;
alter table if exists detalle_examenes_escolares add constraint FKt6ph42qxqlp5uucpr31530n3o foreign key (id_examen_escolar) references examenes_escolares;
alter table if exists detalle_examenes_escolares add constraint FKolb9ki5nggs4yminp1ti4dpx2 foreign key (id_inscripcion_alumno) references inscripcion_alumno;
alter table if exists examenes_escolares add constraint FKon8amrah6spdabidruok07104 foreign key (id_periodo_lectivo) references periodo_academico;
alter table if exists examenes_escolares add constraint FKsy6yavjjnf7qoh0e6ytuhd5wl foreign key (id_materia) references materia;
alter table if exists examenes_escolares add constraint FKrnvpo3d7klaxbst8du1m7vaey foreign key (id_docente) references person;
alter table if exists examenes_escolares add constraint FKtiimf1ybjf63ur938xlq3m0mo foreign key (id_tipo_examen) references tipo_examen;
alter table if exists inscripcion_alumno add constraint FKgvjvqsgp3ohbhxlmigq2b0x4k foreign key (periodo_lectivo_id) references periodo_lectivo;
alter table if exists inscripcion_alumno add constraint FK9ei1jrbf4o0wthx3biakjp1k0 foreign key (nivel_grado_id) references nivel_grado;
alter table if exists inscripcion_alumno add constraint FK7y52anadbc62e532jaeis4uon foreign key (division_id) references division;
alter table if exists inscripcion_alumno add constraint FKlwkl1twg2a2s5xvfouqiop77w foreign key (turno_id) references turno;
alter table if exists inscripcion_alumno add constraint FKhvqijsljg1k3e85xutss71ru1 foreign key (alumno_id) references alumno;
alter table if exists materia add constraint FKe6jwunlrrq8n7jul7o1256vka foreign key (nivel_grado_id) references nivel_grado;
alter table if exists materia add constraint FKpr0074uj62ehkdpawx6ox551i foreign key (docente_id) references person;
alter table if exists tipo_examen add constraint FKnc3e22a497l3gotjyrejkxc0c foreign key (school_exam_id) references examenes_escolares;