FROM node:20 as build-stage

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build --prod

FROM nginx:alpine

COPY nginx.conf /etc/nginx/nginx.conf

COPY --from=build-stage /app/dist/school-management1.1/browser /usr/share/nginx/html

EXPOSE 80

#docker build -t sm-ui/sm-ui:1.0.1 -f path_to_Dockerfile .